<?php 


class EmailverifyTemplate
{
	// funcion para crear el contenido de la pagina
	// los parametros son los datos basicos que contendra el mensaje
	public static function template( $_token, $user_id )
	{
		$body = "
			<html> 
				<body>
					<div style='background: #DB1B1B; color: white; text-align: center; padding: 10px;'>
						<h2><img src='".RUTA_IMG."/logotipo.png' width='300px' height='80px' /></h2>
					</div>
					<div style='background: #efefef; padding: 30px;'>
						<h3>Welcome to TAKEONE SPORTS & TECHNOLOGY! For us it is a pleasure to have you, but we must make sure that this is your email linked to your TAKEONE account, please check it with the following link:</h3>
						<p>
							Url: <a href='".RUTA_URL."/Auth/Verify/".$_token."/".$user_id."/".date('Y-m-d H:i:s')."'>".RUTA_URL."/Auth/Verify/".$_token."/".$user_id."/".date('Y-m-d H:i:s')."</a>
						</p>
						<h4>Remember that the activation of your account will be active while you are logged in on our platform, otherwise you must request another verification email.</h4>
						<h5 style='text-align:center'>
							** Do not respond to this message, it is automatically generated by the web page system **
						</h5>
					</div>
				</body> 
			</html>
		";
		return $body; 
	}
}