<?php 


class RecoverpasswordTemplate
{
	// funcion para crear el contenido de la pagina
	// los parametros son los datos basicos que contendra el mensaje
	public static function template( $nombre, $password )
	{
		$body = "
			<html> 
				<body>
					<div style='background: #DB1B1B; color: white; text-align: center; padding: 10px;'>
						<h2>".APP_NAME."</h2>
					</div>
					<div style='background: #efefef; padding: 30px;'>
						<h4>¡Hello ".ucwords($nombre)."!, we have recived a password update request.</h3>
						<h4>New password: ".$password."</h4>
						<h5 style='text-align:center'>
							** Do not answer this e-mail, it has been automatically generated by the web page's system. **
						</h5>
					</div>
				</body> 
			</html>
		";
		return $body; 
	}
}