<?php 


class SubscriptionreminderTemplate
{
	// funcion para crear el contenido de la pagina
	// los parametros son los datos basicos que contendra el mensaje
	public static function template( $club_title )
	{
		$body = "
			<html> 
				<body>
					<div style='background: #DB1B1B; color: white; text-align: center; padding: 10px;'>
						<h2><img src='".RUTA_IMG."/logotipo.png' width='300px' height='80px' /></h2>
					</div>
					<div style='background: #efefef; padding: 30px;'>
						<h3>Thank you for being part of TAKEONE SPORTS & TECHNOLOGY, we want to remind you that your subscription to the club ".ucwords( $club_title )." is 3 days from expiration.</h3>
						<h5 style='text-align:center'>
							** Do not respond to this message, it is automatically generated by the web page system **
						</h5>
					</div>
				</body> 
			</html>
		";
		return $body; 
	}
}